---
name: williamechols-portfolio build and reploy
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install

    - name: Deploy
      run: |
        git config --global user.name 'William Echols'
        git config --global user.email 'echolswd@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
        npm run deploy